# Identificação do Projeto no SonarCloud
sonar.projectKey=thaynarlt_taskflow-api
sonar.organization=thaynarlt

# Diretório base do código-fonte
sonar.sources=backend/src,frontend

# Testes e cobertura
sonar.tests=backend/src/__tests__
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# Arquivos e pastas a serem ignorados na análise
sonar.exclusions=**/node_modules/**,**/coverage/**,**/__tests__/**

sonar.host.url=https://sonarcloud.io